{% set name = "intensity-normalization" %}
{% set version = "2.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d6f2ac360f51f5314e690272cb26c454e6deab69ef48a7c650ea760247d1d4db

build:
  number: 0
  noarch: python
  entry_points:
    - fcm-normalize=intensity_normalization.cli:fcm_main
    - kde-normalize=intensity_normalization.cli:kde_main
    - lsq-normalize=intensity_normalization.cli:lsq_main
    - nyul-normalize=intensity_normalization.cli:nyul_main
    - ws-normalize=intensity_normalization.cli:ws_main
    - zscore-normalize=intensity_normalization.cli:zs_main
    - plot-histograms=intensity_normalization.cli:histogram_main
    - tissue-membership=intensity_normalization.cli:tissue_main
    - ravel-normalize=intensity_normalization.cli:ravel_main
    - preprocess=intensity_normalization.cli:preprocessor_main
    - coregister=intensity_normalization.cli:register_main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - pytest-runner
  run:
    - matplotlib-base
    - nibabel
    - numpy
    - python >=3.6
    - scikit-fuzzy
    - scikit-image
    - scikit-learn
    - scipy
    - statsmodels
    - pytest-runner

test:
  imports:
    - intensity_normalization
    - intensity_normalization.cli
  commands:
    - fcm-normalize --help
    - kde-normalize --help
    - lsq-normalize --help
    - nyul-normalize --help
    - ws-normalize --help
    - zscore-normalize --help
    - plot-histograms --help
    - tissue-membership --help
  requires:
    - pip

about:
  home: https://github.com/jcreinhold/intensity-normalization
  summary: Normalize the intensity of MR images
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://intensity-normalization.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - sarthakpati
